import type { ProjectSubmission } from "@/types/project";
export const emptySubmission: ProjectSubmission = {
  title: "",
  tagline: "",
  summary: "",
  category: "other",
  stage: "other",
  status: "dead",
  primaryCauseOfDeath: "other",
  causeExplanation: "",
  originalIdea: "",
  whyBuilt: "",
  whatWasBuilt: [],
  whatWentWrong: [],
  whatWorked: [],
  lessons: [],
  survivingAssets: [],
  technologies: [],
  developmentDuration: "",
  developmentPeriod: "",
  estimatedHours: null,
  desiredNextSteps: ["let-it-rest"],
  coverImage: null,
  screenshots: [],
  links: { website: "", github: "", demo: "" },
  creator: { name: "", profileUrl: "", github: "", linkedin: "", x: "" },
  email: "",
  contactUrl: "",
};
